INSERT INTO users(LOGIN,PASSWORD,EMAIL)
VALUES ('admin','admin','admin@mail.ru');

INSERT INTO role(ROLE_ID)
VALUES ('ROLE_ADMIN');
INSERT INTO role(ROLE_ID)
VALUES ('ROLE_USER');
INSERT INTO role(ROLE_ID)
VALUES ('ROLE_GUEST');

INSERT INTO user_role_detail(USER_ID,ROLE_ID)
VALUES (1,'ROLE_ADMIN')

